name: libgame
description: Filesystem based game organization.
dependencies:
  browser: any
  dartemis: any
  barback: any
  stagexl_spine:
    git:
      url: https://github.com/bp74/StageXL_Spine.git
      ref: 6d2f9f5c76b14aaf7e48245d338d79eebf701205
  browser: any
  stagexl: '>=0.12.0-dev <0.13.0'
dependency_overrides:
  stagexl:
    git:
      url: https://github.com/bp74/StageXL.git
      ref: 66d9d08e6ea31bcf961e09856d1265d85e42c42d
transformers:
- libgame